micronaut.application.name=local-object-storage
micronaut.router.static-resources.ui.enabled=true
micronaut.router.static-resources.ui.mapping=/**
micronaut.router.static-resources.ui.paths=classpath:public

datasources.default.url=${JDBC_URL:`jdbc:postgresql://localhost:5433/local_object_storage`}
datasources.default.username=${JDBC_USER:postgres}
datasources.default.password=${JDBC_PASSWORD:postgres}
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.schema-generate=NONE

flyway.datasources.default.enabled=true

micronaut.server.max-request-size=104857600
