micronaut.application.name=local-object-storage
micronaut.router.static-resources.ui.enabled=true
micronaut.router.static-resources.ui.mapping=/**
micronaut.router.static-resources.ui.paths=classpath:public

datasources.default.url=${JDBC_URL:`jdbc:postgresql://localhost:5433/local_object_storage`}
datasources.default.username=${JDBC_USER:postgres}
datasources.default.password=${JDBC_PASSWORD:postgres}
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.db-type=postgres
datasources.default.dialect=POSTGRES
datasources.default.schema-generate=NONE
#datasources.default.maximum-pool-size=20
#datasources.default.minimum-idle=10

flyway.datasources.default.enabled=true

micronaut.server.max-request-size=104857600

endpoints.all.enabled=true
endpoints.all.sensitive=false
endpoints.prometheus.enabled=true
endpoints.prometheus.sensitive=false

micronaut.metrics.enabled=true
micronaut.metrics.binders.files.enabled=true
micronaut.metrics.binders.jvm.enabled=true
micronaut.metrics.binders.logback.enabled=true
micronaut.metrics.binders.processor.enabled=true
micronaut.metrics.binders.uptime.enabled=true
micronaut.metrics.export.prometheus.enabled=true
micronaut.metrics.export.prometheus.step=PT15S

micronaut.executors.blocking.type=fixed
micronaut.executors.blocking.nThreads=64
